diagram_fact(as, cell_10, "geometry").
diagram_fact(as, cell_11, "geometry").
diagram_fact(as, cell_12, "geometry").
diagram_fact(as, cell_13, "geometry").
diagram_fact(as, cell_14, "geometry").
diagram_fact(as, cell_15, "geometry").
diagram_fact(as, cell_16, "geometry").
diagram_fact(as, cell_17, "geometry").
diagram_fact(as, cell_18, "geometry").
diagram_fact(as, cell_19, "geometry").
diagram_fact(as, cell_20, "geometry").
diagram_fact(as, cell_21, "geometry").
diagram_fact(as, cell_22, "geometry").
diagram_fact(as, cell_23, "geometry").
diagram_fact(as, cell_6, "geometry").
diagram_fact(as, cell_7, "geometry").
diagram_fact(as, cell_8, "geometry").
diagram_fact(as, cell_9, "geometry").
diagram_fact(aspect, cell_11, "fixed").
diagram_fact(aspect, cell_12, "fixed").
diagram_fact(aspect, cell_13, "fixed").
diagram_fact(aspect, cell_15, "fixed").
diagram_fact(aspect, cell_17, "fixed").
diagram_fact(aspect, cell_19, "fixed").
diagram_fact(aspect, cell_20, "fixed").
diagram_fact(aspect, cell_22, "fixed").
diagram_fact(aspect, cell_23, "fixed").
diagram_fact(aspect, cell_9, "fixed").
diagram_fact(cell, cell_10, "").
diagram_fact(cell, cell_11, "").
diagram_fact(cell, cell_12, "").
diagram_fact(cell, cell_13, "").
diagram_fact(cell, cell_14, "").
diagram_fact(cell, cell_15, "").
diagram_fact(cell, cell_16, "").
diagram_fact(cell, cell_17, "").
diagram_fact(cell, cell_18, "").
diagram_fact(cell, cell_19, "").
diagram_fact(cell, cell_20, "").
diagram_fact(cell, cell_21, "").
diagram_fact(cell, cell_22, "").
diagram_fact(cell, cell_23, "").
diagram_fact(cell, cell_4, "").
diagram_fact(cell, cell_5, "").
diagram_fact(cell, cell_6, "").
diagram_fact(cell, cell_7, "").
diagram_fact(cell, cell_8, "").
diagram_fact(cell, cell_9, "").
diagram_fact(diagram, diagram_1, "").
diagram_fact(edge, cell_10, 1).
diagram_fact(edge, cell_14, 1).
diagram_fact(edge, cell_16, 1).
diagram_fact(edge, cell_18, 1).
diagram_fact(edge, cell_21, 1).
diagram_fact(edgeStyle, cell_10, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_14, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_16, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_18, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_21, "orthogonalEdgeStyle").
diagram_fact(entryDx, cell_14, 0).
diagram_fact(entryDx, cell_16, 0).
diagram_fact(entryDx, cell_18, 0).
diagram_fact(entryDy, cell_14, 0).
diagram_fact(entryDy, cell_16, 0).
diagram_fact(entryDy, cell_18, 0).
diagram_fact(entryX, cell_14, 0).
diagram_fact(entryX, cell_16, 0).
diagram_fact(entryX, cell_18, 1).
diagram_fact(entryY, cell_14, 0.5).
diagram_fact(entryY, cell_16, 0.5).
diagram_fact(entryY, cell_18, 0.5).
diagram_fact(exitDx, cell_10, 0).
diagram_fact(exitDx, cell_14, 0).
diagram_fact(exitDx, cell_16, 0).
diagram_fact(exitDx, cell_18, 0).
diagram_fact(exitDx, cell_21, 0).
diagram_fact(exitDy, cell_10, 0).
diagram_fact(exitDy, cell_14, 0).
diagram_fact(exitDy, cell_16, 0).
diagram_fact(exitDy, cell_18, 0).
diagram_fact(exitDy, cell_21, 0).
diagram_fact(exitX, cell_10, 1).
diagram_fact(exitX, cell_14, 1).
diagram_fact(exitX, cell_16, 1).
diagram_fact(exitX, cell_18, 0).
diagram_fact(exitX, cell_21, 1).
diagram_fact(exitY, cell_10, 0.5).
diagram_fact(exitY, cell_14, 0.5).
diagram_fact(exitY, cell_16, 0.5).
diagram_fact(exitY, cell_18, 0.5).
diagram_fact(exitY, cell_21, 0.5).
diagram_fact(fillColor, cell_11, "#fff2cc").
diagram_fact(fillColor, cell_12, "#d5e8d4").
diagram_fact(fillColor, cell_13, "#d5e8d4").
diagram_fact(fillColor, cell_15, "#d5e8d4").
diagram_fact(fillColor, cell_17, "#d5e8d4").
diagram_fact(fillColor, cell_19, "#fff2cc").
diagram_fact(fillColor, cell_20, "#d5e8d4").
diagram_fact(fillColor, cell_22, "#fff2cc").
diagram_fact(fillColor, cell_23, "#fff2cc").
diagram_fact(fillColor, cell_9, "#d5e8d4").
diagram_fact(height, cell_11, 40).
diagram_fact(height, cell_12, 40).
diagram_fact(height, cell_13, 40).
diagram_fact(height, cell_15, 40).
diagram_fact(height, cell_17, 40).
diagram_fact(height, cell_19, 40).
diagram_fact(height, cell_20, 40).
diagram_fact(height, cell_22, 40).
diagram_fact(height, cell_23, 40).
diagram_fact(height, cell_6, 260).
diagram_fact(height, cell_7, 180).
diagram_fact(height, cell_8, 120).
diagram_fact(height, cell_9, 40).
diagram_fact(horizontal, cell_6, 1).
diagram_fact(html, cell_10, 1).
diagram_fact(html, cell_11, 1).
diagram_fact(html, cell_12, 1).
diagram_fact(html, cell_13, 1).
diagram_fact(html, cell_14, 1).
diagram_fact(html, cell_15, 1).
diagram_fact(html, cell_16, 1).
diagram_fact(html, cell_17, 1).
diagram_fact(html, cell_18, 1).
diagram_fact(html, cell_19, 1).
diagram_fact(html, cell_20, 1).
diagram_fact(html, cell_21, 1).
diagram_fact(html, cell_22, 1).
diagram_fact(html, cell_23, 1).
diagram_fact(html, cell_6, 1).
diagram_fact(html, cell_7, 1).
diagram_fact(html, cell_8, 1).
diagram_fact(html, cell_9, 1).
diagram_fact(jettySize, cell_10, "auto").
diagram_fact(jettySize, cell_14, "auto").
diagram_fact(jettySize, cell_16, "auto").
diagram_fact(jettySize, cell_18, "auto").
diagram_fact(jettySize, cell_21, "auto").
diagram_fact(kind, cell_11, "ellipse").
diagram_fact(kind, cell_12, "ellipse").
diagram_fact(kind, cell_13, "ellipse").
diagram_fact(kind, cell_15, "ellipse").
diagram_fact(kind, cell_17, "ellipse").
diagram_fact(kind, cell_19, "ellipse").
diagram_fact(kind, cell_20, "ellipse").
diagram_fact(kind, cell_22, "ellipse").
diagram_fact(kind, cell_23, "ellipse").
diagram_fact(kind, cell_9, "ellipse").
diagram_fact(mxGraphModel, mxGraphModel_2, mxGraphModel_2).
diagram_fact(name, diagram_1, "Page-1").
diagram_fact(orthogonalLoop, cell_10, 1).
diagram_fact(orthogonalLoop, cell_14, 1).
diagram_fact(orthogonalLoop, cell_16, 1).
diagram_fact(orthogonalLoop, cell_18, 1).
diagram_fact(orthogonalLoop, cell_21, 1).
diagram_fact(parent, cell_10, id_1).
diagram_fact(parent, cell_11, id_1).
diagram_fact(parent, cell_12, id_1).
diagram_fact(parent, cell_13, id_1).
diagram_fact(parent, cell_14, id_1).
diagram_fact(parent, cell_15, id_1).
diagram_fact(parent, cell_16, id_1).
diagram_fact(parent, cell_17, id_1).
diagram_fact(parent, cell_18, id_1).
diagram_fact(parent, cell_19, id_1).
diagram_fact(parent, cell_20, id_1).
diagram_fact(parent, cell_21, id_1).
diagram_fact(parent, cell_22, id_1).
diagram_fact(parent, cell_23, id_1).
diagram_fact(parent, cell_5, id_0).
diagram_fact(parent, cell_6, id_1).
diagram_fact(parent, cell_7, id_1).
diagram_fact(parent, cell_8, id_1).
diagram_fact(parent, cell_9, id_1).
diagram_fact(relative, cell_10, 1).
diagram_fact(relative, cell_14, 1).
diagram_fact(relative, cell_16, 1).
diagram_fact(relative, cell_18, 1).
diagram_fact(relative, cell_21, 1).
diagram_fact(root, root_3, root_3).
diagram_fact(rounded, cell_10, 0).
diagram_fact(rounded, cell_14, 0).
diagram_fact(rounded, cell_16, 0).
diagram_fact(rounded, cell_18, 0).
diagram_fact(rounded, cell_21, 0).
diagram_fact(rounded, cell_6, 1).
diagram_fact(rounded, cell_7, 1).
diagram_fact(rounded, cell_8, 1).
diagram_fact(source, cell_10, id_LWPhjr7DYTPskbLwUoHT__3).
diagram_fact(source, cell_14, id_LWPhjr7DYTPskbLwUoHT__9).
diagram_fact(source, cell_16, id_LWPhjr7DYTPskbLwUoHT__10).
diagram_fact(source, cell_18, id_LWPhjr7DYTPskbLwUoHT__15).
diagram_fact(source, cell_21, v8j8bDj29g00xxI74zif__1).
diagram_fact(strokeColor, cell_11, "#d6b656").
diagram_fact(strokeColor, cell_12, "#82b366").
diagram_fact(strokeColor, cell_13, "#82b366").
diagram_fact(strokeColor, cell_15, "#82b366").
diagram_fact(strokeColor, cell_17, "#82b366").
diagram_fact(strokeColor, cell_19, "#d6b656").
diagram_fact(strokeColor, cell_20, "#82b366").
diagram_fact(strokeColor, cell_22, "#d6b656").
diagram_fact(strokeColor, cell_23, "#d6b656").
diagram_fact(strokeColor, cell_9, "#82b366").
diagram_fact(synonym, cell_10, id_LWPhjr7DYTPskbLwUoHT__7).
diagram_fact(synonym, cell_11, id_LWPhjr7DYTPskbLwUoHT__3).
diagram_fact(synonym, cell_12, id_LWPhjr7DYTPskbLwUoHT__5).
diagram_fact(synonym, cell_13, id_LWPhjr7DYTPskbLwUoHT__8).
diagram_fact(synonym, cell_14, id_LWPhjr7DYTPskbLwUoHT__12).
diagram_fact(synonym, cell_15, id_LWPhjr7DYTPskbLwUoHT__9).
diagram_fact(synonym, cell_16, id_LWPhjr7DYTPskbLwUoHT__11).
diagram_fact(synonym, cell_17, id_LWPhjr7DYTPskbLwUoHT__10).
diagram_fact(synonym, cell_18, id_LWPhjr7DYTPskbLwUoHT__17).
diagram_fact(synonym, cell_19, id_LWPhjr7DYTPskbLwUoHT__15).
diagram_fact(synonym, cell_20, id_LWPhjr7DYTPskbLwUoHT__16).
diagram_fact(synonym, cell_21, id_HBayNe__pfctkD0sC8m9X__2).
diagram_fact(synonym, cell_22, v8j8bDj29g00xxI74zif__1).
diagram_fact(synonym, cell_23, id_HBayNe__pfctkD0sC8m9X__1).
diagram_fact(synonym, cell_4, id_0).
diagram_fact(synonym, cell_5, id_1).
diagram_fact(synonym, cell_6, id_LWPhjr7DYTPskbLwUoHT__13).
diagram_fact(synonym, cell_7, id_LWPhjr7DYTPskbLwUoHT__4).
diagram_fact(synonym, cell_8, id_LWPhjr7DYTPskbLwUoHT__1).
diagram_fact(synonym, cell_9, id_LWPhjr7DYTPskbLwUoHT__2).
diagram_fact(target, cell_10, id_LWPhjr7DYTPskbLwUoHT__5).
diagram_fact(target, cell_14, id_LWPhjr7DYTPskbLwUoHT__8).
diagram_fact(target, cell_16, id_LWPhjr7DYTPskbLwUoHT__2).
diagram_fact(target, cell_18, id_LWPhjr7DYTPskbLwUoHT__16).
diagram_fact(target, cell_21, id_HBayNe__pfctkD0sC8m9X__1).
diagram_fact(value, cell_11, "char").
diagram_fact(value, cell_12, "char").
diagram_fact(value, cell_13, "filename").
diagram_fact(value, cell_15, "input filename").
diagram_fact(value, cell_17, "output filename").
diagram_fact(value, cell_19, "request").
diagram_fact(value, cell_20, "req").
diagram_fact(value, cell_22, "char").
diagram_fact(value, cell_23, "char").
diagram_fact(value, cell_6, "top").
diagram_fact(value, cell_7, "write").
diagram_fact(value, cell_8, "read").
diagram_fact(value, cell_9, "filename").
diagram_fact(vertex, cell_11, 1).
diagram_fact(vertex, cell_12, 1).
diagram_fact(vertex, cell_13, 1).
diagram_fact(vertex, cell_15, 1).
diagram_fact(vertex, cell_17, 1).
diagram_fact(vertex, cell_19, 1).
diagram_fact(vertex, cell_20, 1).
diagram_fact(vertex, cell_22, 1).
diagram_fact(vertex, cell_23, 1).
diagram_fact(vertex, cell_6, 1).
diagram_fact(vertex, cell_7, 1).
diagram_fact(vertex, cell_8, 1).
diagram_fact(vertex, cell_9, 1).
diagram_fact(verticalAlign, cell_6, "top").
diagram_fact(whiteSpace, cell_11, "wrap").
diagram_fact(whiteSpace, cell_12, "wrap").
diagram_fact(whiteSpace, cell_13, "wrap").
diagram_fact(whiteSpace, cell_15, "wrap").
diagram_fact(whiteSpace, cell_17, "wrap").
diagram_fact(whiteSpace, cell_19, "wrap").
diagram_fact(whiteSpace, cell_20, "wrap").
diagram_fact(whiteSpace, cell_22, "wrap").
diagram_fact(whiteSpace, cell_23, "wrap").
diagram_fact(whiteSpace, cell_6, "wrap").
diagram_fact(whiteSpace, cell_7, "wrap").
diagram_fact(whiteSpace, cell_8, "wrap").
diagram_fact(whiteSpace, cell_9, "wrap").
diagram_fact(width, cell_11, 40).
diagram_fact(width, cell_12, 40).
diagram_fact(width, cell_13, 40).
diagram_fact(width, cell_15, 40).
diagram_fact(width, cell_17, 40).
diagram_fact(width, cell_19, 40).
diagram_fact(width, cell_20, 40).
diagram_fact(width, cell_22, 40).
diagram_fact(width, cell_23, 40).
diagram_fact(width, cell_6, 620).
diagram_fact(width, cell_7, 120).
diagram_fact(width, cell_8, 120).
diagram_fact(width, cell_9, 40).
diagram_fact(x, cell_11, 300).
diagram_fact(x, cell_12, 460).
diagram_fact(x, cell_13, 180).
diagram_fact(x, cell_15, 60).
diagram_fact(x, cell_17, 60).
diagram_fact(x, cell_19, 460).
diagram_fact(x, cell_20, 300).
diagram_fact(x, cell_22, 580).
diagram_fact(x, cell_23, 680).
diagram_fact(x, cell_6, 80).
diagram_fact(x, cell_7, 480).
diagram_fact(x, cell_8, 200).
diagram_fact(x, cell_9, 460).
diagram_fact(y, cell_11, 180).
diagram_fact(y, cell_12, 180).
diagram_fact(y, cell_13, 180).
diagram_fact(y, cell_15, 180).
diagram_fact(y, cell_17, 100).
diagram_fact(y, cell_19, 230).
diagram_fact(y, cell_20, 230).
diagram_fact(y, cell_22, 120).
diagram_fact(y, cell_23, 120).
diagram_fact(y, cell_6, 50).
diagram_fact(y, cell_7, 100).
diagram_fact(y, cell_8, 160).
diagram_fact(y, cell_9, 120).
